export { RegistroPacientePage } from "./registro-paciente/registro-paciente";
export { ElegirPacientePage } from "./elegir-paciente/elegir-paciente";
export { PacientePage } from "./paciente/paciente";
export { VerHclPage }  from  "./ver-hcl/ver-hcl";
export { IdentificacionGeneralPage } from "./identificacion-general/identificacion-general";
export { IdentificacionEncargadosPage } from "./identificacion-encargados/identificacion-encargados";
export { MotivoConsultaPage } from "./motivo-consulta/motivo-consulta";
export { HistoriaFamiliarPage } from "./historia-familiar/historia-familiar";
export { HistoriaEscolarPage } from "./historia-escolar/historia-escolar";
