export class hcl{
  clave :string;
  key :string;
  nombre:string;
  fecha_nac:string;
  edad:number;
  grado:string;
  genero:string;
  colegio:string;
  fecha_entrevista:string;
  entrevistado:string;
  nombre_padre:string;
  fecha_nac_padre:string;
  edad_padre:string;
  profesion_padre:string;
  lugar_trabajo_padre:string;
  nombre_madre:string;
  fecha_nac_madre:string;
  edad_madre:string;
  profesion_madre:string;
  lugar_trabajo_madre:string;
  estado_civil_padres:string;
  motivo:string;
  areas_dificultad:string;
  descripcion_problema:string;
  inicio_problema:string;
  actitud_encargado_problema:string;
  existen_medidad:string;
  medidas_tomadas:string;
  resultados_medidas:string;
  nivel_socioeconomico:string;
  estado_casa:string;
  integracion_familiar:string;
  duerme_solo:string;
  con_quien_vive:string;
  hermanos:string;
  lugar_entre_hermanos:string;
  relacion_papa:string;
  relacion_mama:string;
  relacion_hermanos:string;
  relacion_otros:string;
  disciplina_casa:string;
  medidas_disciplina:string;
  inicio_escolaridad:string;
  adaptacion:string;
  grados_repetidos:string;
  razon_repetidos:string;
  centro_evaluacion:string;
  motivo_cambio:string;
  actitud_institucion_educativa:string;
  interaccion_compañeros:string;
  interaccion_adultos:string;
  rendimiento:string;
  mejores_materias:string;
  peores_materias:string;
  relacion_maestros:string;
  edad_embarazo:string;
  perdidas:string;
  embarazo_deseado:string;
  intento_aborto:string;
  tipo_embarazo:string;
  medicamentos_usados:string;
  anestesia:string;
  control_prenatal:string;
  consumos:string;
  traumas:string;
  enfermedades:string;
  estado_nutricional:string;
  tipo_parto:string;
  tiempo_parto:string;
  presentacion_bebe:string;
  tiempo_llanto:string;
  complicaciones_parto:string;
  otras_complicaciones:string;
  peso_nacer:number;
  talla_nacer:string;
  terapias_especiales:string;
  tipo_lactancia:string;
  enfermedades_significativas:string;
  tratamientos_farmacológicos:string;
  habitos_alimenticios:string;
  habitos_sueño:string;
  vacunas:string;
  antecedentes_neurologicos:string;
  familia_aprendizaje:string;
  familia_intelectual:string;
  familia_lenguaje:string;
  familia_epilepsia:string;
  familia_alcoholismo:string;
  familia_psicosis:string;
  familia_otros:string;
  caracteristicas_emocionales:string;
  caracteristicas_sueño:string;
  caracteristicas_sociales:string;
  caracteristicas_alimentacion:string;
  edad_control_esfinter_vesical_noche:string;
  edad_control_esfinter_vesical_dia:string;
  edad_control_esfinter_anal_noche:string;
  edad_control_esfinter_anal_dia:string;
  musculo_cuello:string;
  levanto_cabeza:string;
  dio_vuelta:string;
  se_sento:string;
  gateo:string;
  paro:string;
  camino:string;
  gorjeo:string;
  sonrisa:string;
  laleo:string;
  balbuceo:string;
  primeras_palabras:string;
  frases_dos_palabras:string;
  oraciones_completas:string;


      constructor(){
        this.key = '';
        this.clave = '';
        this.nombre = '';
        this.fecha_nac= '';
        this.edad = null;
        this.grado= '';
        this.genero= '';
        this.colegio= '';
        this.fecha_entrevista= '';
        this.entrevistado= '';
        this.nombre_padre= '';
        this.fecha_nac_padre= '';
        this.edad_padre= '';
        this.profesion_padre= '';
        this.lugar_trabajo_padre= '';
        this.nombre_madre= '';
        this.fecha_nac_madre= '';
        this.edad_madre= '';
        this.profesion_madre= '';
        this.lugar_trabajo_madre= '';
        this.estado_civil_padres= '';
        this.motivo= '';
        this.areas_dificultad= '';
        this.descripcion_problema= '';
        this.inicio_problema= '';
        this.actitud_encargado_problema= '';
        this.existen_medidad= '';
        this.medidas_tomadas= '';
        this.resultados_medidas= '';
        this.nivel_socioeconomico= '';
        this.estado_casa= '';
        this.integracion_familiar= '';
        this.duerme_solo= '';
        this.con_quien_vive= '';
        this.hermanos= '';
        this.lugar_entre_hermanos= '';
        this.relacion_papa= '';
        this.relacion_mama= '';
        this.relacion_hermanos= '';
        this.relacion_otros= '';
        this.disciplina_casa= '';
        this.medidas_disciplina= '';
        this.inicio_escolaridad= '';
        this.adaptacion= '';
        this.grados_repetidos= '';
        this.razon_repetidos= '';
        this.centro_evaluacion= '';
        this.motivo_cambio= '';
        this.actitud_institucion_educativa= '';
        this.interaccion_compañeros= '';
        this.interaccion_adultos= '';
        this.rendimiento= '';
        this.mejores_materias= '';
        this.peores_materias= '';
        this.relacion_maestros= '';
        this.edad_embarazo= '';
        this.perdidas= '';
        this.embarazo_deseado= '';
        this.intento_aborto= '';
        this.tipo_embarazo= '';
        this.medicamentos_usados= '';
        this.anestesia= '';
        this.control_prenatal= '';
        this.consumos= '';
        this.traumas= '';
        this.enfermedades= '';
        this.estado_nutricional= '';
        this.tipo_parto= '';
        this.tiempo_parto= '';
        this.presentacion_bebe= '';
        this.tiempo_llanto= '';
        this.complicaciones_parto= '';
        this.otras_complicaciones= '';
        this.peso_nacer= null;
        this.talla_nacer= '';
        this.terapias_especiales= '';
        this.tipo_lactancia= '';
        this.enfermedades_significativas= '';
        this.tratamientos_farmacológicos= '';
        this.habitos_alimenticios= '';
        this.habitos_sueño= '';
        this.vacunas= '';
        this.antecedentes_neurologicos= '';
        this.familia_aprendizaje= '';
        this.familia_intelectual= '';
        this.familia_lenguaje= '';
        this.familia_epilepsia= '';
        this.familia_alcoholismo= '';
        this.familia_psicosis= '';
        this.familia_otros= '';
        this.caracteristicas_emocionales= '';
        this.caracteristicas_sueño= '';
        this.caracteristicas_sociales= '';
        this.caracteristicas_alimentacion= '';
        this.edad_control_esfinter_vesical_noche= '';
        this.edad_control_esfinter_vesical_dia= '';
        this.edad_control_esfinter_anal_noche= '';
        this.edad_control_esfinter_anal_dia= '';
        this.musculo_cuello= '';
        this.levanto_cabeza= '';
        this.dio_vuelta= '';
        this.se_sento= '';
        this.gateo= '';
        this.paro= '';
        this.camino= '';
        this.gorjeo= '';
        this.sonrisa= '';
        this.laleo= '';
        this.balbuceo= '';
        this.primeras_palabras= '';
        this.frases_dos_palabras= '';
        this.oraciones_completas= '';
      }

}
