export class perfil{
  clave:string;
  key:string;
  institucion:string;
  fecha_observacion:string;
  dificultades_basicas:string;
  dificultades_academicas:string;
  dificultades_conducta:string;
  fortalezas_basicas:string;
  fortalezas_academicas:string;
  fortalezas_conducta:string;
  criterio1:string;
  criterio2:string;
  criterio3:string;
  criterio4:string;
  criterio5:string;
  observaciones:string;
  autorizado:string;
}
